name: Rust

on: [push]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, windows-latest, windows-2019]

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
